import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="h-screen px-6">
          <div className="max-w-screen-lg h-full flex justify-center items-start flex-col bg-gray-300 mx-auto">
            <span>Helena Strada</span>
            <h1>Software Engineer @ BackEnd</h1>
            <p>
              Atuo como engenheira de software e sou apaixonada por livros e
              tecnologia. Principais interesses em arquitetura de software,
              código limpo e sempre estou buscando algo para aprimorar e/ou
              aprender.
            </p>
          </div>
        </section>
      </main>

      <footer>
        <p>yey</p>
      </footer>
    </div>
  );
};

export default Home;
