version: '3'
name: mssql-server-blog
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Sa#p4ssword"
      MSSQL_PID: Express
    ports:
      - "1433:1433"